INSERT INTO person (first_name, last_name, personal_id) VALUES ('Jan', 'Alexander', 'CZ6555hjhg');
INSERT INTO person (first_name, last_name, personal_id) VALUES ('Jana', 'Alexanderova', 'CZ9');
INSERT INTO person (first_name, last_name, personal_id) VALUES ('Petr', 'Alex', 'CZhhxxc5667');
INSERT INTO person (first_name, last_name, personal_id) VALUES ('Petra', 'Alexova', 'CZuhggy586');
INSERT INTO account (account_number, amount, currency, personal_id) VALUES (1, 20.58, 'CZK', 'CZ6555hjhg');
INSERT INTO account (account_number, amount, currency, personal_id) VALUES (2, 4058.31, 'USD', 'CZ6555hjhg');
INSERT INTO account (account_number, amount, currency, personal_id) VALUES (3, 4058.31, 'EUR', 'CZ6555hjhg');
INSERT INTO account (account_number, amount, currency, personal_id) VALUES (4, 48058.31, 'USD', 'CZ6555hjhg');
INSERT INTO account (account_number, amount, currency, personal_id) VALUES (5, 14058.31, 'USD', 'CZhhxxc5667');
INSERT INTO account (account_number, amount, currency, personal_id) VALUES (6, 994058.31, 'USD','CZuhggy586');